require('dotenv')

module.exports = {
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_REGION: process.env.AWS_REGION,
  TIMESTREAM_REGION: process.env.TIMESTREAM_REGION,
  DEVELOPMENT: process.env.DEVELOPMENT === 'true',
  TS_METRICS_DATABASE: process.env.TS_METRICS_DATABASE, 
  METRICS_STAMP_TABLE: process.env.METRICS_STAMP_TABLE, 
  METRICS_VERIFY_TABLE: process.env.METRICS_VERIFY_TABLE, 
  METRICS_GET_PROOF_TABLE: process.env.METRICS_GET_PROOF_TABLE,
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
  LOGS_PATH: process.env.LOGS_PATH,
  DYNAMO_TABLE: process.env.DYNAMO_TABLE,
  OTS_UPDATE_DELAY_MS: parseInt(process.env.OTS_UPDATE_DELAY_MS || '5000')
}